config/routes.rb
Trabalho::Application.routes.draw do

  resources :profissionals

  resources :empresas

  resources :projetos do
    resources :elaboracaos, :module => :projetos
  end
    
  resource :profissional_sessions, :only => [:create, :new, :destroy]

  root :to => 'home#index'

end

app/models/projeto.rb
class Projeto < ActiveRecord::Base

  belongs_to :profissional, :dependent => :destroy
  
  # Um projeto possui muitas elaborações
  has_many :elaboracaos, :dependent => :destroy
  has_many :elaboracaos_projetos, :through => :elaboracaos, :source => :projeto

  attr_accessible :descricao, :nome, :validade_anos, :valor

  validates_presence_of :descricao, :nome, :validade_anos, :valor

  validates_length_of :nome, :maximum => 255, :allow_blank => false
  validates_uniqueness_of :nome

  validates_length_of :validade_anos, :is => 1, :allow_blank => false
  validates_numericality_of :validade_anos, :only_integer => true, :allow_nil => false

  validates_numericality_of :valor, :only_float => true, :allow_nil => false

  validates_length_of :descricao, :minimum => 50, :allow_blank => false

end

app/controllers/projetos/elaboracaos_controller.rb
class Projetos::ElaboracaosController < ApplicationController
    before_filter :requer_autenticacao

    def new
        @elaboracao = Elaboracao.new
    end

    def create

    end

    def edit

    end

    def update

    end
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController

    before_filter :requer_autenticacao, 
    :only => [:new, :create, :edit, :update, :destroy]

    def index
        @projetos = Projeto.all
    end

    def new
        @projeto = profissional_da_sessao.projetos.build
    end

    def create
        @projeto = profissional_da_sessao.projetos.build(params[:projeto])

        if @projeto.save
            redirect_to @projeto, :notice => 'Projeto criado com sucesso!'
        else
            render :new
        end
    end

    def show
        @projeto = Projeto.find(params[:id])
    end

    def edit
        @projeto = profissional_da_sessao.projetos.find(params[:id])
    end

    def update
        @projeto = profissional_da_sessao.projetos.find(params[:id])

        if @projeto.update_attributes(params[:projeto])
            redirect_to @projeto, :notice => 'Projeto atualizado com sucesso!'
        else
            render :edit
        end
    end


    def destroy
        @projeto = profissional_da_sessao.projetos.find(params[:id])
        @projeto.destroy

        redirect_to projetos_url
    end
    
end

app/views/projetos/_form.html.erb
<% if @projeto.errors.any? %>
    <div id="error_explanation">
        Há erros no formulário, por favor verifique.
    </div>
<% end %>

<%= form_for @projeto do |p| %>
    <p>
        <%= p.label :nome %>
        <%= p.text_field :nome %>
        <%= error_tag @projeto, :nome %>
    </p>
    <p>
        <%= p.label :descricao %>
        <%= p.text_area :descricao %>
        <%= error_tag @projeto, :descricao %>
    </p>
    <p>
        <%= p.label :valor %>
        <%= p.text_field :valor %>
        <%= error_tag @projeto, :valor %>
    </p>
    <p>
        <%= p.label :validade_anos %>
        <%= p.text_field :validade_anos %>
        <%= error_tag @projeto, :validade_anos %>
    </p>
    <p>
        <%= p.submit %>
    </p>
<% end %>

app/views/projetos/_projeto.html.erb
<article class="projeto_empresa">
    <h2><%= link_to projeto.nome, projeto %></h2>
    <span>
        <%= t '.proprietario_html',
            :proprietario => projeto.profissional.nome,
            :quando => l(projeto.created_at, :format => :short) %>
    </span>

    <p>
        Valor: <%= projeto.valor %> —
        Validade em anos: <%= projeto.validade_anos %>
    </p>

    <p><%= projeto.descricao %></p>

    <% if belongs_to_profissional(projeto) %>
        <ul>
            <li><%= link_to "Editar", edit_projeto_path(projeto) %></li>
            <li><%= link_to "Remover", projeto_path(projeto),
                        :method => :delete, :data => 
                        {:confirm => 'Você tem certeza que quer remover?'}
                %></li>
        </ul>
    <% end %>
</article>

app/views/projetos/edit.html.erb
<h1>Editar projeto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', @projeto %>

app/views/projetos/index.html.erb
<h1>Projetos Disponíveis</h1>

<%= render @projetos %>

app/views/projetos/new.html.erb
<h1>Cadastro de Projeto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', root_path %>

app/views/projetos/show.html.erb
<%= render @projeto %>