config/routes.rb
Trabalho::Application.routes.draw do

  resources :profissionals

  resources :empresas

  resources :projetos do
    resources :elaboracaos, :module => :projetos
  end
    
  resource :profissional_sessions, :only => [:create, :new, :destroy]

  root :to => 'home#index'

end

app/models/profissional.rb
class Profissional < ActiveRecord::Base

  has_many :projetos, :dependent => :destroy
  has_many :empresas, :dependent => :destroy
  
  # Um profissional possui muitas elaborações
  has_many :elaboracaos, :dependent => :destroy

  attr_accessible   :email, :especialidade, :nome, :registro, :password,
                    :telefone, :password_confirmation

  validates_presence_of :email, :especialidade, :nome, :registro, :password, :password_confirmation

  #Validação de tamanho
  validates_length_of :nome, :maximum => 100, :allow_blank => false
  validates_length_of :email, :especialidade, :registro, :password, :maximum => 50, :allow_blank => false
  validates_length_of :telefone, :maximum => 13, :allow_blank => true

  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  
  validates_uniqueness_of :email, :registro

  has_secure_password

  scope :login, where('email IS NOT NULL')

  def self.authenticate(email, password)
    login.
    find_by_email(email).
    try(:authenticate, password)
  end
end

app/controllers/profissionals_controller.rb
class ProfissionalsController < ApplicationController

    before_filter :nao_requer_autenticacao, :only => [:new, :create]
    before_filter :pode_alterar, :only => [:edit, :update]

    def new
        @profissional = Profissional.new
    end

    def create
        @profissional = Profissional.new(params[:profissional])

        if @profissional.save
            redirect_to @profissional, :notice => 'Profissional criado com sucesso!'
        else
            render :new
        end
    end

    def show
        @profissional = Profissional.find(params[:id])
    end

    def edit
        @profissional = Profissional.find(params[:id])
    end

    def update
        @profissional = Profissional.find(params[:id])

        if @profissional.update_attributes(params[:profissional])
            redirect_to @profissional, :notice => 'Profissional atualizado com sucesso!'
        else
            render :edit
        end
    end

    # Não permite a vizualização e edição do perfil dos outros profissionais

    private 

    def pode_alterar
        unless profissional_autenticado? && profissional_da_sessao == profissional
            redirect_to Profissional.find(params[:id]),
            :alert => 'Não é pertida a edição do perfil alheio!'
        end
    end

    def profissional
        @profissional ||= Profissional.find(params[:id])
    end

end

app/views/profissionals/_form.html.erb
<% if @profissional.errors.any? %>
    <div id="error_explanation">
        Há erros no formulário, por favor verifique.
    </div>
<% end %>

<%= form_for @profissional do |p| %>
    <p>
        <%= p.label :nome %>
        <%= p.text_field :nome %>
        <%= error_tag @profissional, :nome %>
    </p>
    <p>
        <%= p.label :telefone %>
        <%= p.text_field :telefone %>
        <%= error_tag @profissional, :telefone %>
    </p>
    <p>
        <%= p.label :email %>
        <%= p.text_field :email %>
        <%= error_tag @profissional, :email %>
    </p>
    <p>
        <%= p.label :especialidade %>
        <%= p.text_field :especialidade %>
        <%= error_tag @profissional, :especialidade %>
    </p>
    <p>
        <%= p.label :registro %>
        <%= p.text_field :registro %>
        <%= error_tag @profissional, :registro %>
    </p>
    <p>
        <%= p.label :password %>
        <%= p.password_field :password %>
        <%= error_tag @profissional, :password %>
    </p>
    <p>
        <%= p.label :password_confirmation %>
        <%= p.password_field :password_confirmation %>
        <%= error_tag @profissional, :password_confirmation %>
    </p>
    <p>
        <%= p.submit %>
    </p>

<% end %>

app/views/profissionals/edit.html.erb
<h1>Editar profissional</h1>

<%= render 'form' %>

<%= link_to 'Voltar', @profissional %>

app/views/profissionals/new.html.erb
<h1>Cadastro de Profissional</h1>

<%= render 'form' %>

<%= link_to 'Voltar', root_path %>

app/views/profissionals/show.html.erb
<h1>Profisional: <%= @profissional.nome%></h1>
<ul>
    <li>E-mail: <%= @profissional.email %></li>
    <li>Especialidade: <%= @profissional.especialidade %></li>
    <li>Registro: <%= @profissional.registro %></li>
</ul>

<%= link_to 'Editar Profissional', edit_profissional_path(@profissional) %> | 
<%= link_to 'Home', root_path %>