config/routes.rb
Trabalho::Application.routes.draw do

  resources :profissionals

  resources :empresas

  resources :projetos do
    resources :elaboracaos, :module => :projetos
  end
    
  resource :profissional_sessions, :only => [:create, :new, :destroy]

  root :to => 'home#index'

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base

  belongs_to :profissional, :dependent => :destroy

  # Uma empresa possui muitas elaborações
  has_many :elaboracaos, :dependent => :destroy

  INTERVALO = (1..4).to_a

  attr_accessible :atividade_principal, :bairro, :cep, :cidade, 
  :cnae, :cnpj, :complemento, :email, :grau_risco, :inscricao_estadual, 
  :nome_empresarial, :nome_fantasia, :nome_logradouro, 
  :numero_logradouro, :telefone, :uf

  validates_presence_of :cnpj, :nome_empresarial, :grau_risco, :cnae, 
  :atividade_principal, :email, :cep, :nome_logradouro, :bairro, :uf, :cidade

  # Validação de tamanho
  validates_length_of :cnpj, :maximum => 18, :allow_blank => false
  validates_length_of :inscricao_estadual, :maximum => 12, :allow_blank => true
  validates_length_of :nome_empresarial, :nome_logradouro, :maximum => 100, :allow_blank => false
  validates_length_of :nome_fantasia, :maximum => 100, :allow_blank => true

  validates_inclusion_of :grau_risco, :in => INTERVALO
  ######

  validates_length_of :cnae, :cep, :maximum => 10, :allow_blank => false
  validates_length_of :atividade_principal, :minimum => 10, :allow_blank => false
  validates_length_of :telefone, :maximum => 13, :allow_blank => true
  validates_length_of :email, :bairro, :cidade, :maximum => 50, :allow_blank => false

  validates_numericality_of :numero_logradouro, :only_integer => true, :allow_nil => true

  validates_length_of :uf, :is => 2, :allow_blank => false
  validates_length_of :complemento, :maximum => 50, :allow_blank => true

  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  validates_uniqueness_of :cnpj, :email
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController

    before_filter :requer_autenticacao, 
    :only => [:new, :create, :edit, :update, :destroy]

    def index
        @empresas = Empresa.all
    end

    def new
        @empresa = profissional_da_sessao.empresas.build
    end

    def create
        @empresa = profissional_da_sessao.empresas.build(params[:empresa])

        if @empresa.save
            redirect_to @empresa, :notice => 'Empresa criada com sucesso!'
        else
            render :new
        end
    end

    def show
        @empresa = Empresa.find(params[:id])
    end

    def edit
        @empresa = profissional_da_sessao.empresas.find(params[:id])
    end

    def update
        @empresa = profissional_da_sessao.empresas.find(params[:id])

        if @empresa.update_attributes(params[:empresa])
            redirect_to @empresa, :notice => 'Empresa atualizada com sucesso!'
        else
            render :edit
        end
    end

    def destroy
        @empresa = profissional_da_sessao.empresas.find(params[:id])
        @empresa.destroy

        redirect_to empresas_url
    end

end

app/views/empresas/_empresa.html.erb
<article class="projeto_empresa">
    <h2><%= link_to empresa.nome_empresarial + " (" + empresa.nome_fantasia + ")", empresa %></h2>
    <span>
        <%= t '.proprietario_html',
            :proprietario => empresa.profissional.nome,
            :quando => l(empresa.created_at, :format => :short) %>
    </span>

    <p>CNPJ: <%= empresa.cnpj %></p>
    <p>Grau de risco: <%= empresa.grau_risco %></p>
    <p>CNAE: <%= empresa.cnae %></p>
    <p>Atividade Principal: <%= empresa.atividade_principal %></p>
    <p>Email: <%= empresa.email %></p>    

    <% palavra = empresa.nome_logradouro + ", " + 
                empresa.numero_logradouro.to_s + " - " +
                empresa.bairro + ". " +
                empresa.cidade + "-" + empresa.uf + ". " +
                empresa.cep + ". " +
                empresa.complemento
    %>

    <% palavra1 = empresa.nome_fantasia + ". " + palavra + ". Brasil" %>

    <p>
        <span>
            Endereço: 
            <%= link_to palavra, 
                "https://maps.google.com/?q=#{palavra1}",
                :target => :blank
            %>
        </span>
    </p>

    <% if belongs_to_profissional(empresa) %>
        <ul>
            <li><%= link_to "Editar", edit_empresa_path(empresa) %></li>
            <li><%= link_to "Remover", empresa_path(empresa),
                        :method => :delete, :data => 
                        {:confirm => 'Você tem certeza que quer remover?'}
                %></li>
        </ul>
    <% end %>
</article>

app/views/empresas/_form.html.erb
<% if @empresa.errors.any? %>
    <div id="error_explanation">
        Há erros no formulário, por favor verifique.
    </div>
<% end %>

<%= form_for @empresa do |e| %>
    <p>
        <%= e.label :cnpj %>
        <%= e.text_field :cnpj %>
        <%= error_tag @empresa, :cnpj %>
    </p>
    <p>
        <%= e.label :inscricao_estadual %>
        <%= e.text_field :inscricao_estadual %>
        <%= error_tag @empresa, :inscricao_estadual %>
    </p>
    <p>
        <%= e.label :nome_empresarial %>
        <%= e.text_field :nome_empresarial %>
        <%= error_tag @empresa, :nome_empresarial %>
    </p>
    <p>
        <%= e.label :nome_fantasia %>
        <%= e.text_field :nome_fantasia %>
        <%= error_tag @empresa, :nome_fantasia %>
    </p>
    <p>
        <%= e.label :grau_risco %>
        <%= e.text_field :grau_risco %>
        <%= error_tag @empresa, :grau_risco %>
        <!-- Alterar o tipo de campo aqui -->
    </p>
    <p>
        <%= e.label :cnae %>
        <%= e.text_field :cnae %>
        <%= error_tag @empresa, :cnae %>
    </p>
    <p>
        <%= e.label :atividade_principal %>
        <%= e.text_area :atividade_principal %>
        <%= error_tag @empresa, :atividade_principal %>
    </p>
    <p>
        <%= e.label :telefone %>
        <%= e.text_field :telefone %>
        <%= error_tag @empresa, :telefone %>
    </p>
    <p>
        <%= e.label :email %>
        <%= e.text_field :email %>
        <%= error_tag @empresa, :email %>
    </p>
    <p>
        <%= e.label :cep %>
        <%= e.text_field :cep %>
        <%= error_tag @empresa, :cep %>
    </p>
    <p>
        <%= e.label :nome_logradouro %>
        <%= e.text_field :nome_logradouro %>
        <%= error_tag @empresa, :nome_logradouro %>
    </p>
    <p>
        <%= e.label :numero_logradouro %>
        <%= e.text_field :numero_logradouro %>
        <%= error_tag @empresa, :numero_logradouro %>
    </p>
    <p>
        <%= e.label :bairro %>
        <%= e.text_field :bairro %>
        <%= error_tag @empresa, :bairro %>
    </p>
    <p>
        <%= e.label :uf %>
        <%= e.text_field :uf %>
        <%= error_tag @empresa, :uf %>
        <!-- Alterar o tipo de campo aqui -->
    </p>
    <p>
        <%= e.label :cidade %>
        <%= e.text_field :cidade %>
        <%= error_tag @empresa, :cidade %>
    </p>
    <p>
        <%= e.label :complemento %>
        <%= e.text_field :complemento %>
        <%= error_tag @empresa, :complemento %>
    </p>
    <p>
        <%= e.submit %>
    </p>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editar Empresa</h1>

<%= render 'form' %>

<%= link_to 'Voltar', @empresa %>

app/views/empresas/index.html.erb
<h1>Empresas Disponíveis</h1>

<%= render @empresas %>

app/views/empresas/new.html.erb
<h1>Cadastro de Empresa</h1>

<%= render 'form' %>

<%= link_to 'Voltar', root_path %>

app/views/empresas/show.html.erb
<%= render @empresa %>