config/routes.rb
Trabalho::Application.routes.draw do

  resources :profissionals

  resources :empresas

  resources :projetos do
    resources :elaboracaos, :module => :projetos
  end
    
  resource :profissional_sessions, :only => [:create, :new, :destroy]

  root :to => 'home#index'

end

app/views/layouts/_profissional_navbar.html.erb
<nav>
    <ul>
        <li><%= link_to "Cad Empresas", new_empresa_path %></li>
        <li><%= link_to "Cad Projetos", new_projeto_path %></li>
        <li><%= link_to "Meu perfil", profissional_path(profissional_da_sessao) %></li>
        <li><%= link_to "Sair", profissional_sessions_path, :method => :delete %></li>
    </ul>
</nav>

app/views/layouts/_visitante_navbar.html.erb
<nav>
    <ul>
        <li><%= link_to "Empresas", empresas_path %></li>
        <li><%= link_to "Projetos", projetos_path %></li>
        <li><%= link_to "Cadastro", new_profissional_path %></li>
        <li><%= link_to "Login", new_profissional_sessions_path %></li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Rails</title>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Pacifico">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
        <div id="header-wrap">
            <h1><%= link_to "Ruby on Rails", root_path %></h1>
            <% if profissional_autenticado? %>
                <%= render '/layouts/profissional_navbar' %>
            <% else %>
                <%= render '/layouts/visitante_navbar' %>
            <% end %>
        </div>
    </header>

    <div id="content">
        <% if notice.present?  %>
            <p id="notice"><%= notice %></p>
        <% end %>
        <% if alert.present? %>
            <p id="alert"><%= alert %></p>
        <% end %>
        
        <%= yield %>
    </div>
</body>
</html>